project:
  type: book

book:
  title: "Data 7 Exploratory Data Analysis In R Workshops Companion Book"
  author: "Greg Chism"
  cover-image: cover.png
  chapters:
    - index.qmd
    - intro.qmd
    - DiagnosingLikeDataDoctor.qmd
    - ExploringLikeDataAdventurer.qmd
    - TransformingLikeDataTrans.qmd
    - ImputatingLikeDataScientist.qmd
    - CorrelateLikeDataMaster.qmd
  repo-url: https://github.com/Gchism94/Data7_EDA_In_R_Workshops

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-copy: true



