project:
  type: book

book:
  title: "Data 7 Exploratory Data Analysis In R Workshops Companion Book"
  author: "Greg Chism"
  date: "8/8/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - DiagnosingLikeDataDoctor.qmd
    - ExploringLikeDataAdventurer.qmd
    - TransformingLikeDataTrans.qmd
    - ImputatingLikeDataScientist.qmd
    - CorrelateLikeDataMaster.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



