project:
  type: book

book:
  title: "Exploratory Data Analysis In R Book"
  author: "Greg Chism"
  cover-image: cover.png
  chapters:
    - index.qmd
    - intro.qmd
    - DiagnosingLikeDataDoctor.qmd
    - ExploringLikeDataAdventurer.qmd
    - TransformingLikeDataTrans.qmd
    - ImputingLikeDataScientist.qmd
    - CorrelateLikeDataMaster.qmd
  repo-url: https://github.com/Gchism94/EDA_In_R_Workshops

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-copy: true



